name = "VEDSViz"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["VEDS Team"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieFramework = "46a6dbbe-9cf4-4d1b-b0f2-45bce96ab33f"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Redis = "0cf705f9-a9e2-5763-9cd4-5c4ffc3c63ff"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1abb-4b0e-9d61-9d4d0b7bdfa3"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
julia = "1.10"
